apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: control-tower-uat-test
spec:
  workload:
    name: ct
    source:
        repo: https://github.com/eedorenko/control-tower
        branch: main
        path: .
    application:
        name: control-tower              
        workspace:
            name: demo-team
  deploymentTarget:
    name: uat-test
    environment: stage-gray
    manifests:
        repo: https://github.com/eedorenko/control-tower-gitops
        branch: stage-gray
        path: ./uat-test
  workloadVersion:
    version: 0.0.1-10
    commit: fb21472d22abb73c8f494ae2e00099a7c8c7c66f