apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: control-tower-functional-test
spec:
  workload:
    name: ct
    source:
        repo: https://github.com/eedorenko/control-tower
        branch: main
        path: .
    application:
        name: control-tower              
        workspace:
            name: demo-team
  deploymentTarget:
    name: functional-test
    environment: dev-green
    manifests:
        repo: https://github.com/eedorenko/control-tower-gitops
        branch: dev-green
        path: ./functional-test
  workloadVersion:
    version: 0.0.1-4
    commit: 636ad11ee7e9e3f8d9d47634a50b6bec18de10c6