apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: control-tower-functional-test
spec:
  workload:
    name: ct
    source:
        repo: https://github.com/eedorenko/control-tower
        branch: main
        path: .
    application:
        name: control-tower              
        workspace:
            name: demo-team
  deploymentTarget:
    name: functional-test
    environment: dev-gray
    manifests:
        repo: https://github.com/eedorenko/control-tower-gitops
        branch: dev-gray
        path: ./functional-test
  workloadVersion:
    version: 0.0.1-12
    commit: e702180f1ddae1cc66b84f63bf8adc40195b4011